name: image-e2e-tests
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main

jobs:
  test:    
    name: Test non user docker
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test docker amd64 non-user with KCL version
        run: docker run --user=999 --rm kcllang/kcl sh -c "kcl version"
      - name: Test docker amd64 non-user with KCL running
        run: docker run --user=999 --rm kcllang/kcl sh -c "echo 'a=1' | kcl run -"
      - name: Test docker arm64 non-user with KCL version
        run: docker run --platform linux/arm64 --user=999 --rm kcllang/kcl sh -c "kcl version"
      - name: Test docker arm64 non-user with KCL running
        run: docker run --platform linux/arm64 --user=999 --rm kcllang/kcl sh -c "echo 'a=1' | kcl run -"
