name: image-e2e-tests
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main

jobs:
  test:    
    name: Test non user docker
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.11.2
          install: true
      - name: Test docker non-user
        run: docker run --user=999 --rm kcllang/kcl sh -c "echo 'a=1' | kcl run -"
